sudo: required
services: 
    - docker

before_install:
    - docker build -t sumeetchawladocker/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true sumeetchawladocker/docker-react npm run test -- --coverage
    