#Specify the base image
FROM node:alpine

#Setting the working directory
WORKDIR '/app'

#COPY file package.json to container file system
COPY package.json .

#Install dependencies
RUN npm install

COPY . .

#Default command
CMD ["npm", "run", "start"]